yarnPath: .yarn/releases/yarn-4.1.0.cjs

nodeLinker: pnp

compressionLevel: mixed

enableGlobalCache: false

# 로컬 이외에도 CI 등 모든 종류의 Runtime에서 잘 작동할 수 있도록 아키텍쳐를 전부 선언해놓아요
supportedArchitectures:
  cpu:
    - ia32
    - x86
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
