/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const AddRestaurantLazyImport = createFileRoute('/add-restaurant')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const CompaniesCompnayIdLazyImport = createFileRoute('/companies/$compnayId')()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const AddRestaurantLazyRoute = AddRestaurantLazyImport.update({
  path: '/add-restaurant',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/add-restaurant.lazy').then((d) => d.Route),
)

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CompaniesCompnayIdLazyRoute = CompaniesCompnayIdLazyImport.update({
  path: '/companies/$compnayId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/companies.$compnayId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/add-restaurant': {
      preLoaderRoute: typeof AddRestaurantLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/companies/$compnayId': {
      preLoaderRoute: typeof CompaniesCompnayIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  AddRestaurantLazyRoute,
  LoginLazyRoute,
  CompaniesCompnayIdLazyRoute,
])

/* prettier-ignore-end */
